version: '3'
services:
    db:
        image: postgres
        container_name: postgres_db
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    app:
        container_name: code
        build: .
        tty: true
        ports:
            - "9000:9000"
        command: go run main.go
        volumes:
            - .:/go/src/work
        depends_on: 
            - db